version: "3.6"

services:
  accounting:
    build: accounting-microservice/
    command: bash -c "flask run"
    restart: on-failure
    environment:
      HOST: 0.0.0.0
      PORT: 5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"