import os

USER_MICROSERVICE_URL = os.environ.get("USER_MICROSERVICE_URL")
ACCOUNTING_MICROSERVICE_URL = os.environ.get("ACCOUNTING_MICROSERVICE_URL")
PRODUCT_MICROSERVICE_URL = os.environ.get("PRODUCT_MICROSERVICE_URL")
DEFAULT_CURRENCY_CODE = os.environ.get("DEFAULT_CURRENCY_CODE", "KES")

HOST = os.environ.get("HOST", "0.0.0.0")
PORT = os.environ.get("PORT", 5001)

